- name: Homepage
  description: Dashboard for services
  tag: homepage
  api:
    method: GET
    url: https://home.jojonosaur.us/
  image: "/home.png"

- name: Svelte Website
  description: Cybernetically enhanced web apps
  tag: "svelte-website"
  api:
      method: GET
      url: https://svelte.dev/
  image: "/svelte.svg"

- name: Earth
  description: Our blue planet
  tag: "earth"
  defaultStatus: "UP"
  image: "/earth.png"

- name: IBM Server
  description: Linux Server Nginx
  tag: "ibm"
  api:
      method: GET
      url: https://ibm.jojonosaur.us/
  image: "/cloud.png"
  