title: "Status"
home: "/"
logo: "/logo.png"
github:
    owner: "jojoclt"
    repo: "kener"
    incidentSince: 48
metaTags:
    description: "Kener: Open-source modern looking Node.js status page tool, designed to make service monitoring and incident handling a breeze. It offers a sleek and user-friendly interface that simplifies tracking service outages and improves how we communicate during incidents. And the best part? Kener integrates seamlessly with GitHub, making incident management a team effort—making it easier for us to track and fix issues together in a collaborative and friendly environment."
    keywords: "Node.js status page, Incident management tool, Service monitoring, Service outage tracking, Real-time status updates, GitHub integration for incidents, Open-source status page, Node.js monitoring application, Service reliability, User-friendly incident management, Collaborative incident resolution, Seamless outage communication, Service disruption tracker, Real-time incident alerts, Node.js status reporting"
    og:description: "Kener: Open-source Node.js status page tool, designed to make service monitoring and incident handling a breeze. It offers a sleek and user-friendly interface that simplifies tracking service outages and improves how we communicate during incidents. And the best part? Kener integrates seamlessly with GitHub, making incident management a team effort—making it easier for us to track and fix issues together in a collaborative and friendly environment."
    og:image: "https://kener.ing/ss.png"
    og:title: "Kener - Open-Source and Modern looking Node.js Status Page for Effortless Incident Management"
    og:type: "website"
    og:site_name: "Kener"
    twitter:card: "summary_large_image"
    twitter:site: "@_rajnandan_"
    twitter:creator: "@_rajnandan_"
    twitter:image: "https://kener.ing/ss.png"
    twitter:title: "Kener: Open-Source and Modern looking Node.js Status Page for Effortless Incident Management"
    twitter:description: "Kener: Open-source Node.js status page tool, designed to make service monitoring and incident handling a breeze. It offers a sleek and user-friendly interface that simplifies tracking service outages and improves how we communicate during incidents. And the best part? Kener integrates seamlessly with GitHub, making incident management a team effort—making it easier for us to track and fix issues together in a collaborative and friendly environment."
nav:
    - name: "Blog"
      url: "https://jojonosaur.us"
    - name: "Github"
      url: "https://github.com/jojoclt/kener"
hero:
    title: Status Page
    subtitle: For Monitoring Uptime for Jojonosaurus Services
footerHTML: |
    Made using 
    <a href="https://github.com/rajnandan1/kener" target="_blank" rel="noreferrer" class="font-medium underline underline-offset-4">
      Kener
    </a>
    an open source status page system built with Svelte and TailwindCSS.
i18n:
    defaultLocale: "en"
    locales:
        en: "English"
        zh-CN: "中文"
        ja: "日本語"
theme: dark
